version: '3.8'

services:
  my-portfolio:
    build: .
    container_name: my-portfolio
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./content:/app/content
      - ./dist:/app/dist
    ports:
      - "8082:8080"
    command: gridsome develop
